In [6]:
import numpy as np
import pandas as pd

In [ ]:
  ------>>> Series From Lists <<<--------

In [2]:
# String
country = ['India', 'Pakistan', 'Nepal', 'Srilanka']
pd.Series(country)

0       India
1    Pakistan
2       Nepal
3    Srilanka
dtype: object

In [3]:
# Integer
runs = [55, 34, 89,123, 5]
pd.Series(runs)

0     55
1     34
2     89
3    123
4      5
dtype: int64

In [35]:
# Custom index
marks = [78, 92, 93, 82]
subjects = ['math', 'english', 'hindi', 'science']
pd.Series(marks, index = subjects)

math       78
english    92
hindi      93
science    82
dtype: int64

In [37]:
# setting a name
marks = pd.Series(marks,index = subjects, name = 'Nitish ke Marks')
marks

math       78
english    92
hindi      93
science    82
Name: Nitish ke Marks, dtype: int64

In [ ]:
       ------->> Series From Dict <<-------

In [5]:
marks = {
    'marks' : 67,
    'english' : 57,
    'science' : 89,
    'hindi' : 100
}
marks_series = pd.Series(marks, name = 'Ajeet ke marks')
marks_series

marks       67
english     57
science     89
hindi      100
Name: Ajeet ke marks, dtype: int64

In [ ]:
---------->>>> Series Attribute <<<<----------

In [5]:
# size
marks_series.size

4

In [7]:
# dtype
print(marks_series.dtype)

int64

In [6]:
# name
marks_series.name

'Ajeet ke marks'

In [11]:
# is_unique
marks_series.is_unique

True

In [ ]:
# index
marks_series.index

In [7]:
# values
marks_series.values

array([ 67,  57,  89, 100])

In [ ]:
----------->>>> Series using read_csv <<<<-----------

In [11]:
cars = pd.read_csv("cars.csv")
cars

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [ ]:
---------->>>> Series Method <<<<---------

In [ ]:
# head and tail

In [6]:
cars.head(2)

    brand  km_driven    fuel         owner  selling_price
0  Maruti     145500  Diesel   First Owner         450000
1   Skoda     120000  Diesel  Second Owner         370000

In [8]:
cars.tail()

        brand  km_driven    fuel                 owner  selling_price
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

In [ ]:
# sample

In [11]:
cars.sample(3)

        brand  km_driven    fuel        owner  selling_price
4373    Skoda     150000  Diesel  Third Owner         280000
2143  Hyundai      60000  Diesel  First Owner         822000
3234   Maruti      38000  Diesel  First Owner         740000

In [ ]:
# value_counts

In [13]:
cars.value_counts()

brand   km_driven  fuel    owner         selling_price
Jaguar  45000      Diesel  First Owner   3200000          34
Lexus   20000      Petrol  First Owner   5150000          34
Toyota  68089      Petrol  First Owner   2000000          32
Honda   56494      Petrol  First Owner   550000           32
Toyota  79328      Diesel  Second Owner  750000           31
                                                          ..
Jeep    12000      Diesel  First Owner   1500000           1
        10000      Petrol  First Owner   1520000           1
Jaguar  70000      Diesel  Second Owner  3000000           1
        35000      Diesel  First Owner   3500000           1
Volvo   72500      Diesel  Second Owner  1200000           1
Name: count, Length: 6450, dtype: int64

In [ ]:
# sort_value
cars.sort_value # ------>> (ye run nhi hoga kyuki cars_csv file iske liye sahi nhi hai.)
cars.sort_value(ascending = False) # -------->> isse value lowest se highest sort hogi.

In [ ]:
cars.sort_value(inplace = True) # ( ye original value me changes kar deta hai. So be careful.)

In [10]:
# sort_index
cars.sort_index()
cars.sort_index(inplace = True)

In [ ]:
---------->>>> Series maths Methods <<<<----------

In [12]:
#count
cars.count()

brand            8128
km_driven        8128
fuel             8128
owner            8128
selling_price    8128
dtype: int64

In [13]:
# sum and product
cars.sum()
cars.prod

brand            MarutiSkodaHondaHyundaiMarutiHyundaiMarutiMaru...
km_driven                                                567492984
fuel             DieselDieselPetrolDieselPetrolPetrolLPGPetrolD...
owner            First OwnerSecond OwnerThird OwnerFirst OwnerF...
selling_price                                           5187873253
dtype: object

In [17]:
# mean/median/mode/std/van
cars.mean()
cars.median()
cars.mode()
cars.std()
cars.var()

In [ ]:
# min/max
cars.min()
cars.max()

In [18]:
# describe ------->> Sumary deta hai
cars.describe()

          km_driven  selling_price
count  8.128000e+03   8.128000e+03
mean   6.981951e+04   6.382718e+05
std    5.655055e+04   8.062534e+05
min    1.000000e+00   2.999900e+04
25%    3.500000e+04   2.549990e+05
50%    6.000000e+04   4.500000e+05
75%    9.800000e+04   6.750000e+05
max    2.360457e+06   1.000000e+07